import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/header";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "@/components/ui/sonner";
// import ThemeToggle from "@/components/theme-toggle"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CareerGuideAi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-gray-100 via-white to-gray-200 min-h-screen`}
      >
        {/* ✅ ClerkProvider must wrap inside <body>, not around <html> */}
        <ClerkProvider
          publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <main className="pt-20 pb-20 min-h-[calc(100vh-120px)]">
              {children}
            </main>
            <Toaster />

            <div className="fixed bottom-4 right-4 z-50">
              {/* <ThemeToggle suppressHydrationWarning /> */}
            </div>

            <footer className="fixed bottom-0 w-full bg-gradient-to-r from-gray-900 via-gray-800 to-gray-700 py-3 shadow-lg border-t border-gray-800">
              <div className="container mx-auto px-6 text-center text-gray-200 font-semibold tracking-wide">
                <p>
                  All rights reserved &copy; {new Date().getFullYear()}{" "}
                  CareerGuideAI
                </p>
              </div>
            </footer>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
